language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
- npm run build
deploy:
  provider: heroku
  app: eaardal-build-and-deploy-2018
  api_key:
    secure: ah4aKbX7LRA8Av1xU+XRpZ7cGyJl3U1/44bXI+XjWOEXWgBeFD1slDodb9nuC0Kle5647iYqsvyNJijuzu2/MKILXo7aCjB3s68w1LvPBrl74oyEQZ+saSNs5m7CA5smBqpHWXq/kiu9dRtkgcUZv6IEZbYxx35BXwBZXPqsmfiMXAKBLOUV48H9Of8lqzY0HEe0RM4uZIRG3UMB0/38xZxPVNY/ZqmRgQgAKO1/C6x//x9+aGmCI3wSuUFg8xNSZpBVvbXPoEtiUE6ViiM2MTYw9ocO7x66aYZlLR+ulOe7Xw8FAekJnz/x/ES8A9jkO/Rt9HYGwI/6I94q9PVMq2hl34xFzTOiVQm+cy1cr4mtG80qT/w4KWCBjAeyVOEAyV7d4IFlT9G/o48GWAdjhtAIt8TFwd9pWH3XznOIqrNrhZEPwZnPR5TlBrqY79H1GkQZ4d3nm00WP2XpEDWavZsyXNOa6SemF39gsu6mIcunHdCrTyinapc9h/T5mABWHFsnfezYJeDK5ST6Od3WBjulCZ7ocMx57xCPoSS5bze+Htr+aNvLlu+/Zk+dqkjNNM8Em8BVlj57Jwod7KZRd5Qu24swocHBVXqGf40Bty3HQXCJTtV9voNeTcNGd5mOKNWWz+0rCA6n5Heuu82kBq6K6MdprCsJelGXpm8UhY4=
